# Config file for automatic testing at travis-ci.org
language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_TYPE="django18"
    - python: "3.3"
      env: TEST_TYPE="django18"
    - python: "3.5"
      env: TEST_TYPE="django18"
    - python: "3.5"
      env: TEST_TYPE="django19"
    - python: "3.5"
      env: TEST_TYPE="django110"
    - python: "3.5"
      env: TEST_TYPE="django111"
    - python: "3.4"
      env: TEST_TYPE="django20"
    - python: "3.6"
      env: TEST_TYPE="django20"
    - python: "2.7"
      env: TEST_TYPE="checkmanifest"
    - python: "2.7"
      env: TEST_TYPE="flake8"
    - python: "2.7"
      env: TEST_TYPE="isort"

install:
- pip install tox>=2.1 tox-travis
- pip install coveralls coverage
addons:
  firefox: "latest"
script:
- coverage erase
- tox
after_success:
- coverage combine
- coveralls
sudo: false
