# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - TEST_TYPE="django18"
  - TEST_TYPE="django19"
  - TEST_TYPE="django110"
  - TEST_TYPE="django111"
matrix:
  include:
    - python: "2.7"
      env: TEST_TYPE="checkmanifest"
    - python: "2.7"
      env: TEST_TYPE="flake8"
    - python: "2.7"
      env: TEST_TYPE="isort"
    - python: "3.3"
      env: TEST_TYPE="django18"

install:
- pip install tox>=2.1 tox-travis
- pip install coveralls coverage
# This doesn't work - https://github.com/travis-ci/travis-ci/issues/9362
# addons:
#   firefox: "45.2.0"
script:
- coverage erase
- test -z "${TEST_TYPE##*django*}" && ./download_firefox.sh
- TEST_FIREFOX_BINARY=`pwd`/downloads/firefox-sdk/bin/firefox tox
after_success:
- coverage combine
- coveralls
sudo: false
